### ISSUE TITLE
現状整理

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/lot#1]
ja ファイルは github から clone し en-US ファイルは get-en-US タスクで hg.mozilla.org の mozilla-central, comm-central のファイルのローカルコピーから集め、ja ファイルを convert, compare しながら更新して完了したら git push する流れになっている: https://dev.mozilla.jp/2009/10/sync/

手元に mozilla-central, comm-central のクローンを持たずに済むようサーバ側で get-en-US したファイルの zip を http://ftp-developer.mozilla-japan.org/pub/mozilla-japan/l10n-tools/resources/mozilla-aurora/en-US/ などに用意してそれを取得する download-en-US タスクも用意している。

少なくとも get-en-US (download-en-US), convert, compare (同時にするエラーチェック群) が必要でそれぞれ適当に ant+groovy じゃなくて python or grunt などのシンプルなものに分離したいなーというのが現状。

**Comment by marsf** [comment]
obsoleted.
