### ISSUE TITLE
クロスチャンネルおよび L20n 対応

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/lot#4]
Gecko 57.0 以降、本家の L10n はクロスチャンネルのリポジトリーに移行したため、ツールもそれに対応する必要がある。
加えて、現状の Ant + Groovy では L20n ([Fluent](http://projectfluent.org/)) 対応が難しい。

必要な機能の要件をしぼってツールを整えたい。

Gulp script 版はこちら → [l10n-tools](https://github.com/mozilla-japan/l10n-tools)

**Comment by marsf** [comment]
add *.ftl to the target utf8files  https://github.com/mozilla-japan/lot/commit/37f9c640e8413cca659a9b417c2b310972f0a61a
.filter での用語置き換え対象に追加。 errorcheck 周りは未確認。

add _configs/ of gecko-strings repo to compare.excludes list https://github.com/mozilla-japan/lot/commit/dcad3dec5ad39385c0c40563d213f8df34ee5bdc
gecko-strings repo を /l10n/en-US ディレクトリに置くため。

**Comment by marsf** [comment]
browser/preferences のファイルが Fluent 形式に移行されます。
[Migration of Preferences strings to Fluent - mozilla.dev.l10n](https://groups.google.com/forum/#!topic/mozilla.dev.l10n/vR3YPhalCE4)
```
Here’s the expected timeline:

  * Land the patch from bug 1411012 in mozilla-central.
  * Expose the new strings in gecko-strings-quarantine.
  * Pause Pontoon’s sync (we’ll send an email to the mailing list when
    this happens).
  * Run the migration and push changes to all l10n-central repositories.
  * Push the new content to gecko-strings.
  * Restart Pontoon’s sync (we’ll send another email).

For this first batch of strings, we expect the migration to last about
an hour, unless there are new issues that we didn’t encounter during the
previous tests. 
```


[Bug 1411012 - Experimentally migrate a small chunk of .properties/.DTD to Fluent](https://bugzilla.mozilla.org/show_bug.cgi?id=1411012)

**Comment by marsf** [comment]
lot で ftl ファイルに対応するためのメモ

[/build.errorcheck.xml](https://github.com/mozilla-japan/lot/blob/dcad3dec5ad39385c0c40563d213f8df34ee5bdc/build.errorcheck.xml#L40)
```
@@ -56,6 +56,7 @@
 		ant.fileset(dir:properties.'syntaxcheck.dir', includes:includes, excludes:excludes).each { file ->
 			if (file =~ /\.properties$/) validpattern = /${properties.'RE.properties.validline'}\n/
 			else if (file =~ /\.dtd$/)   validpattern = /${properties.'RE.dtd.validblock'}\n/
+			else if (file =~ /\.ftl$/)   validpattern = /${properties.'RE.ftl.validblock'}\n/
 			else if (file =~ /\.inc$/)   validpattern = /${properties.'RE.inc.validline'}\n/
 			else if (file =~ /\.ini$/)   validpattern = /${properties.'RE.ini.validline'}\n/
 			else return
```


[/compare.groovy](https://github.com/mozilla-japan/lot/blob/dcad3dec5ad39385c0c40563d213f8df34ee5bdc/compare.groovy#L38)
```
@@ -38,12 +38,14 @@ failonerror = args[9] == 'true'
 patternset = [
 	properties: [header: properties.'RE.properties.header', entityblock: properties.'RE.properties.entityblock', footer: properties.'RE.properties.footer', l10ncomment: properties.'RE.properties.l10ncomment'],
 	dtd: [header: properties.'RE.dtd.header', entityblock: properties.'RE.dtd.anyentityblock', footer: properties.'RE.dtd.footer', l10ncomment: properties.'RE.dtd.l10ncomment'],
+	ftl: [header: properties.'RE.ftl.header', entityblock: properties.'RE.ftl.entityblock', footer: properties.'RE.ftl.footer', l10ncomment: properties.'RE.ftl.l10ncomment'],
 	inc: [header: properties.'RE.inc.header', entityblock: properties.'RE.inc.entityblock', footer: properties.'RE.inc.footer', l10ncomment: properties.'RE.inc.l10ncomment'],
 	ini: [header: properties.'RE.ini.header', entityblock: properties.'RE.ini.entityblock', footer: properties.'RE.ini.footer', l10ncomment: properties.'RE.ini.l10ncomment']
 ]
 filetypeset = [
 	properties: [encoding: 'UTF-8', pattern:patternset.properties, commentheader: "# ", commentfooter: ""],
 	dtd: [encoding: 'UTF-8', pattern:patternset.dtd, commentheader: "<!-- ", commentfooter: " -->"],
+	ftl: [encoding: 'UTF-8', pattern:patternset.ftl, commentheader: "//", commentfooter: ""],
 	inc: [encoding: 'UTF-8', pattern:patternset.inc, commentheader: "#", commentfooter: ""],
 	ini: [encoding: 'UTF-8', pattern:patternset.ini, commentheader: "#", commentfooter: ""]
 ]	
@@ -70,6 +72,7 @@ def parse(dir, file, preprocess, postprocess) {
 	filekey  = file.toString().replaceAll("\\\\", "/").replaceAll("$dir/","").replaceAll("/$locale1|$locale2","/*")
 	if (filekey =~ /\.properties$/) filetype = filetypeset.properties
 	else if (filekey =~ /\.dtd$/)   filetype = filetypeset.dtd
+	else if (filekey =~ /\.ftl$/)   filetype = filetypeset.ftl
 	else if (filekey =~ /\.inc$/)   filetype = filetypeset.inc
 	else if (filekey =~ /\.ini$/)   filetype = filetypeset.ini
 	else return
```

[/res/const.conf](https://github.com/mozilla-japan/lot/blob/master/res/const.conf)
```
+RE.ftl.comment		= [//!][^\\n]*
+RE.ftl.id		= [-0-9a-zA-Z_.?/^{@}]+
+RE.ftl.value		= ...
+RE.ftl.entity		= ...

(以下、ftl の構文定義の正規表現を記述する必要あり。)
```

**Comment by marsf** [comment]
[Fluent Syntax Guide](http://projectfluent.org/fluent/guide/)

https://github.com/projectfluent/fluent/tree/master/spec

**Comment by marsf** [comment]
[Bug 1347801 - Land MessageContext in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1347801)

[MessageContext.jsm](https://dxr.mozilla.org/mozilla-central/source/intl/l10n/MessageContext.jsm)
> 1) Parser (lines 38 - 804)
> 2) Resolver (lines 934 - 1377)
> 3) MessageContext class (lines 1392 - 1582)

**Comment by marsf** [comment]
memo: pontoon / [fluent-syntax.js](https://github.com/mozilla/pontoon/blob/master/pontoon/base/static/js/lib/fluent-syntax.js)

**Comment by dynamis** [comment]
OS 別の用語を分ける (動的に読み込ませる) ための関数は Platform で、複数行になるのが必須かどうかはともかく、読み書きしにくすぎて泣ける
https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/functions.html
```
    .label =
        { PLATFORM() ->
            [macos] Choose…
           *[other] Browse…
        }
```


{ -brand-name } のように ja / ja-JP-mac で訳し分ける必要のある用語は { -window } とか { -paste } とか行った形で参照でき、その定義は上記の Platform 関数で書くというのであれば、メンテナンス性としては許容範囲になるのではないか。
https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/brand_names.html

具体的にはこんな感じなら使い物になるという想定。但し実行時のパフォーマンスが良くないのは目に見えているため、ビルド時に置き換え処理を行うべき。
```
    -window =
        { PLATFORM() ->
            [macos] ウインドウ
           *[other] ウィンドウ
        }
    some-entity = { -window } をなんちゃらかんちゃら
```

Mozilla がどうしようとしているのが、何ができる環境になっているのか要確認。。。

**Comment by marsf** [comment]
[lot-conv.py](https://github.com/marsf/lot-conv) に移行したので close。
