### ISSUE TITLE
Rewrite lot

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/lot#5]
現在 #4 記載の通り l10n リソースは ftl 形式に移行しつつあるがそちらの word check ができるツールがないため、ja/ja-JP-mac での用語訳し分けの見落としなどを避けながら更新を続けるのが難しくなりつつある。既存コードを改修するのはあまり望ましくないためさっと書き直したものが欲しい。

必須要件は次の通り:
- [ ] 古典的なツールを使わずに最新の node なり python なりで処理できること
  - [ ] netlify とかの自動ビルド環境でさっと Web 出力できるとなお良い
- [ ] Platform 非依存の実装となること (Windows/Mac/Linux で実行可能)
- [ ] word check が Allow, Deny のリストとして指定できること
  - [ ] カンマ区切りのリストとして指定できれば十分
  - [ ] 正規表現が書ける必要は必ずしもないが、あってもよい
  - [ ] DTD ファイル
    - https://www.npmjs.com/package/dtd-file
    - https://www.npmjs.com/package/dtdanalyzer
  - [ ] properties ファイル
    - 読み込んで get() で値を getKeys() でキーリストを得る https://www.npmjs.com/package/java-properties
    - JS オブジェクトツリーに変換 https://www.npmjs.com/package/java.properties.js
    - https://www.npmjs.com/package/java-properties-flat-loader
  - [ ] FTL ファイル
    - https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/
    - 読み込み側のライブラリ https://www.npmjs.com/package/fluent
    - 構文パースする側のライブラリ https://www.npmjs.com/package/fluent-syntax 
      - http://projectfluent.org/fluent.js/fluent-syntax/
      - https://github.com/projectfluent/fluent.js/tree/master/fluent-syntax
      - 多分 pontoon で使っているのもこれ
- [ ] word check エラーの発生箇所が分かること
  - [ ] できればエンティティ名として分かるように
  - [ ] 行数も分かるのが望ましい (行数だけでもダメではない)

存続していて欲しい要件:
- [ ] ファイル中の ja/ja-JP-mac 専用文字列置き換え処理
  - https://www.npmjs.com/package/replace-in-file を使ってやるのがよさそう
  - Stream 内で処理するなら https://www.npmjs.com/package/replacestream
- [ ] チェック対象ファイルを簡単に絞り込む

あると望ましい要件:
- [ ] 変更されたファイルを監視してリアルタイムにエラーチェックを行い出力し続ける機能

メモ:
- gulp script で書きかけていたもの https://github.com/mozilla-japan/l10n-tools
  - 文字列置き換えと syntax check までが実装、一番必要な wordcheck 未実装だった
  - gulp script 依存よりも普通に node プログラムにすれば良かったように思う

今すぐはちょっと手を動かす時間が取れません (誰かやってくれる人いればお願いします) が、ひとまず現状の整理とさっと実装に適切そうな node module を調べてみたメモです

**Comment by marsf** [comment]
convert 部分のみ、Python で書き直しました。
https://github.com/marsf/lot-conv

単純に指定ディレクトリ内のファイルを行単位で読み込んで置き換えています。
エラーチェック関連は別のスクリプトにして、最終的にはバッチ処理でよいのではないかと思ってます。

```
> hg diff ... (gecko-strings)
> [edit files]
> compare-locales
> lot-conv.py
> lot-proof.py
```

**Comment by marsf** [comment]
@dynamis 
Python で書き直しました。この issue はクローズしたいと思います。
https://github.com/marsf/lot-conv

gecko 129.0 からほぼすべての l10n ソースが Github に移行したので、ちょうどよい区切りとして、このリポジトリーの lot を引退させます。お世話になりました。 m(_ _)m


適当なときに、lot-conv / lot-proof を mozilla-japan アカウントのリポジトリーに移した方がいいでしょうか？
